### ISSUE TITLE
Permission to share the generated texts

### ISSUE THREAD

**Issue by abevieiramota** [AmitMY/chimera#10]
Hi, 

thanks for the paper _Step-by-Step: Separating Planning from Realization in Neural Data-to-Text Generation_ and for sharing the code.

I'm using WebNLG benchmark in my masters and I'd like to compare the texts generated by various models, so I'd like to know if I can copy the texts generated by your models* to my [repository](https://github.com/abevieiramota/masters/tree/master/data/models), adding a README.md pointing to this repository.

\* I'm assuming they are in /AmitMY/chimera/tree/master/data/WebNLG/compare, named BIU_random_0.txt, BIU_random_1.txt, BIU_random_2.txt and BIU_nmt.txt

**Comment by AmitMY** [comment]
I'm so sorry for the late response, I missed the notification for this.

`BIU_nmt.txt` is what we call `StrongNeural` in the paper. (which is a baseline)

`BIU_chimera` is the name of the file for this final system, but I don't see it in the repo for some reason. I'll push it to the repo as soon as I'm back from ACL (next week)

Feel free to use both.

**Comment by abevieiramota** [comment]
Thanks @AmitMY. I'm looking forward to it.

**Comment by abevieiramota** [comment]
Hi @AmitMY , just a reminder about the BIU_chimera file.

**Comment by AmitMY** [comment]
It is in a different branch right now, but you can access it:
https://github.com/AmitMY/chimera/blob/development/data/WebNLG/compare/BIU_Chimera_v1.txt

v2 will come out after the v2 paper gets accepted (hopefully soon).
