### ISSUE TITLE
Fix errors in misspellings

### ISSUE THREAD

**Issue by Shimorina** [AmitMY/chimera#12]
Hi Amit,

I started revising WebNLG to fix typos, and integrated the misspellings you found.
However, [this](https://github.com/AmitMY/chimera/blob/e367678ef51e0cff6c01c5376fc9849a14f81271/data/WebNLG/reader.py#L86) should be "rector" and [this](https://github.com/AmitMY/chimera/blob/e367678ef51e0cff6c01c5376fc9849a14f81271/data/WebNLG/reader.py#L89) should be something else, but not "runway".

Thanks!

**Comment by AmitMY** [comment]
Thanks!
I revised those.
