### ISSUE TITLE
Data used in 6.2 Manual Evaluation

### ISSUE THREAD

**Issue by abevieiramota** [AmitMY/chimera#13]
Hi Amit,

thanks again for this work. 

I was reading again your paper and I'm wondering if the answers collected for the fluency evaluation, and for the plan realization consistency evaluation are available or can be made available.

**Comment by AmitMY** [comment]
All the evaluation judgments are saved in:
https://github.com/AmitMY/chimera/tree/master/manual-evaluation

For fluency, I couldn't find the evaluation file, it was a CSV downloaded from AMT. If in the future I'll access to this AMT account, I'll download it again and push.
