### ISSUE TITLE
pipeline error

### ISSUE THREAD

**Issue by xhades-pub** [AmitMY/chimera#14]
hi friend:
when I run pipeline, got error:
```
  File "../utils/pipeline.py", line 148, in execute
    x_params=x_params.union(params), previous_name=pn)
  File "../utils/pipeline.py", line 154, in execute
    params[qi.key] = qi.method(params, x_params)
  File "../process/reg.py", line 8, in <lambda>
    lambda _, x: x["config"].reg(x["pre-process"]["train"], x["pre-process"]["dev"]))
TypeError: 'NoneType' object is not callable
```

**Comment by AmitMY** [comment]
Hi,
what is the exact command you ran?

**Comment by xhades-pub** [comment]
Python3.6 server.py

**Comment by AmitMY** [comment]
First, you must run `python main.py` which will run the entire pipeline, and cache the models and results, then you can run the server.

If running the `main` file fails for you, please write down the error here

**Comment by xhades-pub** [comment]
when run python main.py got errors:
![image](https://user-images.githubusercontent.com/54498107/71141955-c5d4b100-2250-11ea-93ec-d6cb9660a04f.png)

**Comment by AmitMY** [comment]
Thanks.
Did you change anything?
Here is the output I get with no-cache, when running:
```py
python main.py
```
https://pastebin.com/91dV7MwH

And here is the output I get when running it after the cache was created:
https://pastebin.com/KKSL33zy

**Comment by xhades-pub** [comment]
Thanks, I re-cloned the repo, and it run.😊

**Comment by AmitMY** [comment]
Awesome!
