### ISSUE TITLE
Question about detail report in EXPERIMENTS.md

### ISSUE THREAD

**Issue by jzhoubu** [AmitMY/chimera#17]
Hi, thanks for sharing this work.  I want to test the performance when beam_size=1, and I found some related information on this [page](https://github.com/AmitMY/chimera/blob/2327cdcfeed181e0b431ba3cc079b313aaa05bf7/EXPERIMENTS.md). Could you introduce a bit more about the second part `Greedy best neural plan`?

- There are multiple results (e.g. 45.97, 43.76, 43.74...),  I am confused about which number should represent the final result when beam_size is 1

- The number list below for `Greedy `(e.g. 45.97) seems even higher than when `beam_size=10`. Could you point me out there?

- I also want to confirm that is the result report on the paper (47.4) generate at beam_size=50?

Many thanks.

**Comment by AmitMY** [comment]
The numbers you should rely on are numbers averaged from multiple runs.
https://arxiv.org/pdf/1909.09986.pdf
The table in the appendix shows the stable numbers

![image](https://user-images.githubusercontent.com/5757359/77657114-83bcb900-6f7d-11ea-950f-27d9271a767b.png)
