### ISSUE TITLE
Global direction Expert

### ISSUE THREAD

**Issue by GivanTsai** [AmitMY/chimera#21]
On the global direction expert of test-time plan selection, Here is a sentence:

_"We capture this tendency using an expert that considers the conditional probability p(nr = n∣ ∣G∣) of observing
n reversed edges in an input with ∣G∣ triplets."_

What are the meaning of nr and probability counted here?

And the plan selection is aimed to Text plan. not to sentence plan?

**Comment by AmitMY** [comment]
`nr` means "`n`umber of `r`eversed" in this case.
so given a graph of size `|G|`, what is the probability to have `n` reversed edges?

> And the plan selection is aimed to Text plan. not to sentence plan?

Yes, this expert considers the entire text plan, not an individual sentence plan. It might be interesting to add an additional sentence level "sentence direction" expert, however this one is "global"

**Comment by GivanTsai** [comment]
> `nr` means "`n`umber of `r`eversed" in this case.
> so given a graph of size `|G|`, what is the probability to have `n` reversed edges?
> 
> > And the plan selection is aimed to Text plan. not to sentence plan?
> 
> Yes, this expert considers the entire text plan, not an individual sentence plan. It might be interesting to add an additional sentence level "sentence direction" expert, however this one is "global"

For a given graph, the size _|G|_ and its reversed edges _nr_ are deterministic. So, for all potential plans originating from this graph,  are scores the same?

And I saw you have published two great papers considering data2text, [the first version](https://arxiv.org/pdf/1904.03396.pdf) and [improved one](https://arxiv.org/pdf/1909.09986v1.pdf), which one does this repository service for?

**Comment by AmitMY** [comment]
This specific expert will indeed score every plan with the same number of reversed edges for the same number of graph edges.

This repo includes both papers, actually, the main difference is the choice of the planner (`NeuralPlanner` for the second paper) and the second paper including extras like REG, and k-best reranking.

**Comment by GivanTsai** [comment]
> This specific expert will indeed score every plan with the same number of reversed edges for the same number of graph edges.
> 
> This repo includes both papers, actually, the main difference is the choice of the planner (`NeuralPlanner` for the second paper) and the second paper including extras like REG, and k-best reranking.

If scores for all candidate plans are the same, what's the role of global direction expert? Because I think it makes no difference to the product of experts.

**Comment by AmitMY** [comment]
It is not equal probability for each, for example -
`P(1 | 5) != P(2 | 5)  != P(3 | 5)  != P(4 | 5)  != P(5 | 5)`

but given a graph with 5 edges, the `global` expert gives an equal probability for each of the plans with 1 reversed edge, regardless of which edge it is.

**Comment by GivanTsai** [comment]
> It is not equal probability for each, for example -
> `P(1 | 5) != P(2 | 5) != P(3 | 5) != P(4 | 5) != P(5 | 5)`
> 
> but given a graph with 5 edges, the `global` expert gives an equal probability for each of the plans with 1 reversed edge, regardless of which edge it is.

Got it! Thanks, AmitMY! It means that we want the plan to use more reversed relations.
