### ISSUE TITLE
Update OpenNMT for mac support

### ISSUE THREAD

**Issue by pedrocolon93** [AmitMY/chimera#3]
Another thing, when trying to run the server I get this
```
in chimera/server on  master [?] pedro🅒 chimera took 16s
☃ ☞  /Users/pedro/anaconda3/envs/chimera/bin/python3 /Users/pedro/Documents/git/chimera/model/../libs/OpenNMT/preprocess.py -train_src /var/folders/ds/s277rjy10757gqy93wzbj2zh0000gn/T/tmpp5w4h0m2 -train_tgt /var/folders/ds/s277rjy10757gqy93wzbj2zh0000gn/T/tmpvjs4y0u8 -valid_src /var/folders/ds/s277rjy10757gqy93wzbj2zh0000gn/T/tmpi_xl8h5_ -valid_tgt /var/folders/ds/s277rjy10757gqy93wzbj2zh0000gn/T/tmpz76g5m_6 -save_data /var/folders/ds/s277rjy10757gqy93wzbj2zh0000gn/T/tmpfybw2hlu/data -dynamic_dict
Traceback (most recent call last):
  File "/Users/pedro/Documents/git/chimera/model/../libs/OpenNMT/preprocess.py", line 15, in <module>
    from onmt.utils.logging import init_logger, logger
  File "/Users/pedro/Documents/git/chimera/libs/OpenNMT/onmt/__init__.py", line 4, in <module>
    import onmt.inputters
  File "/Users/pedro/Documents/git/chimera/libs/OpenNMT/onmt/inputters/__init__.py", line 6, in <module>
    from onmt.inputters.inputter import make_features, collect_features, \
  File "/Users/pedro/Documents/git/chimera/libs/OpenNMT/onmt/inputters/inputter.py", line 19, in <module>
    from onmt.utils.logging import logger
  File "/Users/pedro/Documents/git/chimera/libs/OpenNMT/onmt/utils/__init__.py", line 4, in <module>
    from onmt.utils.statistics import Statistics
  File "/Users/pedro/Documents/git/chimera/libs/OpenNMT/onmt/utils/statistics.py", line 7, in <module>
    from torch.distributed import get_rank
ImportError: cannot import name 'get_rank' from 'torch.distributed' (/Users/pedro/anaconda3/envs/chimera/lib/python3.7/site-packages/torch/distributed/__init__.py)
(chimera)

```
This is on a new conda environment.  I looked into it, and turns out there is a problem in OpenNMT:
[(https://github.com/OpenNMT/OpenNMT-py/issues/1129)]
(I think this may be only for mac that doesnt have cuda).  The fix is to go into 
libs/OpenNMT/ and do a `git checkout 2a2621d770adb593942d7999a59401aff35d646a`.

In this repo you can change the setup.sh to clone that specific commit or do a git checkout for that specific commit. It should not affect anything else.  

Thanks!

**Comment by AmitMY** [comment]
Thanks for the issue.
Just to make sure - this repo clones tag 0.7.0 (`git clone --branch 0.7.0 https://github.com/OpenNMT/OpenNMT-py.git OpenNMT`) 

Because the issue you referenced is referenced in a [PR from January](https://github.com/OpenNMT/OpenNMT-py/pull/1206), could you please try 0.8.2 on your mac? and let me know if it is solved for you?

* The 0.7.0 lock was just so everything works out of the box instead of "latest", we can bump the version if that works for you

**Comment by pedrocolon93** [comment]
With 0.8.2 I get, so I would guess we would need 0.7.1 or something similar rather than 0.7.0:
```
AttributeError: Can't get attribute 'TextDataset' on <module 'onmt.inputters.text_dataset' from '/Users/pedro/Documents/git/chimera/libs/OpenNMT/onmt/inputters/text_dataset.py'>
(chimera)
```

**Comment by pedrocolon93** [comment]
Just checked it with 0.7.1 and it seems to be working fine.

**Comment by AmitMY** [comment]
Thanks for your help figuring this out!
Changed to 0.7.1
