### ISSUE TITLE
Missing download for punkt

### ISSUE THREAD

**Issue by pedrocolon93** [AmitMY/chimera#4]
This error comes up trying to run the system:
`**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')

  Attempted to load tokenizers/punkt/PY3/english.pickle

  Searched in:
    - '/home/pedro/nltk_data'
    - '/home/pedro/anaconda3/nltk_data'
    - '/home/pedro/anaconda3/share/nltk_data'
    - '/home/pedro/anaconda3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************`

Its a simple fix, just add in some python file or on a python command line:
```
import nltk
nltk.download('punkt')
```

**Comment by AmitMY** [comment]
Thanks! I added this as an install step to `setup.sh`:
https://github.com/AmitMY/chimera/blob/8f6df059868b52245267a327ad296f9bb1b72d67/setup.sh#L5
