### ISSUE TITLE
StrongNeural Baseline system

### ISSUE THREAD

**Issue by XinyuHua** [AmitMY/chimera#7]
Dear Amit,

Thanks for the great work! I am trying to replicate the StrongNeural baseline described in your paper, but I failed to find it in this repository. Is there any chance for the baseline code to be released as well? Or in case I missed it could you please point me to the correct file? Thanks! 

P.S. I attempted to send you an email to the gmail address listed in the paper but the mail delivery service couldn't find it.

**Comment by AmitMY** [comment]
`StrongNeural` is not a part of this repo as it is very poorly written, with many attempts on top of other attempts to make it better, and as it is not the main idea of the paper, just a baseline, I would not like to support it.

Eventually, this is just a simple seq2seq like model, with attention, a copy mechanism, and a neural checklist (+ so much unused code), so I would advise trying the original checklist model - https://github.com/uwnlp/neural-checklist.

Here is the model's code - https://pastebin.com/efwCTkQ4
Including hyperparameter tuning with a genetic algorithm, and including graph-lstms which I just made up but eventually didn't use, and including a not-exactly-beam search
*But*, even I would not try to use this code again, instead I would rather implement a checklist mechanism for OpenNMT or something.

---

Regarding the email. Weird, can you write down what address you tried?

**Comment by XinyuHua** [comment]
Thanks, I will try their code first then.

The email address I used was `amitmoryosef@gmail.com`, copied from this [link](https://arxiv.org/pdf/1904.03396.pdf), I guess there's a typo in it as there are two "s" in your name but only one in the email address...

**Comment by AmitMY** [comment]
What a big fail on my part. Yes, my email includes 2 "s" in it :)
(Fixed, new version will be published Friday)
