### ISSUE TITLE
The corpus extended with matching plans

### ISSUE THREAD

**Issue by zhaochaocs** [AmitMY/chimera#8]
Hi Amit,

Happy to see this great paper with very nice results!

Could you let me know where to find the generated matching plans? It is mentioned in the paper but I cannot find it. It seems it's not easy to run the model on a single PC, so I am wondering if the plans can also be released. Thanks.

**Comment by AmitMY** [comment]
Oops, forgot to post those files :)
I just pushed those in the development branch - https://github.com/AmitMY/chimera/tree/development - which is not stable if you want to run the entire process (making some improvements) but is a bit more up-to-date.

Checkout the README under "Enriched Corpus" or just go to the directory https://github.com/AmitMY/chimera/blob/development/git-assets/enriched

**Comment by AmitMY** [comment]
I would add one thing, unrelated to the main issue - 
If you are interested in building a better translation model for surface realization, I highly recommend just extending [this ](https://github.com/AmitMY/chimera/blob/development/model/model_runner.py) `Model` and `ModelRunner` classes, as that would work nice with this entire framework, and benefit from all the improvements we are making, and be easier to experiment with :)

**Comment by zhaochaocs** [comment]
Thanks for the corpus and the kind suggestions. They help a lot :)
